"""
Elevation and 3D building outline schemas.

All spatial values are in metres.
"""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class RoofType(StrEnum):
    FLAT = "flat"          # Flat slab (common in Nepal urban)
    GABLE = "gable"        # Pitched gable roof
    TERRACE = "terrace"    # Accessible flat roof / terrace


class ElevationFace(StrEnum):
    FRONT = "front"
    REAR = "rear"
    LEFT = "left"
    RIGHT = "right"


class OpeningType(StrEnum):
    WINDOW = "window"
    DOOR = "door"
    GARAGE = "garage"


# ---------------------------------------------------------------------------
# Wall opening (door or window) on an elevation face
# ---------------------------------------------------------------------------


class WallOpening(BaseModel):
    opening_type: OpeningType
    floor: int                    # 1-indexed floor number

    # Position on the elevation face (metres from left edge of face)
    position_x: float
    # Bottom of opening from floor level (metres)
    sill_height: float = 0.9      # 0 for doors, 0.9 for windows
    width: float = 1.2
    height: float = 1.2


# ---------------------------------------------------------------------------
# Single floor band on a face (horizontal line between floors)
# ---------------------------------------------------------------------------


class FloorBand(BaseModel):
    floor: int           # The floor this band belongs to
    bottom_z: float      # Metres from ground — bottom of this floor
    top_z: float         # Metres from ground — top of this floor (floor_height)


# ---------------------------------------------------------------------------
# Single elevation view (one face of the building)
# ---------------------------------------------------------------------------


class ElevationView(BaseModel):
    face: ElevationFace
    face_width: float           # metres — full width of this elevation
    total_height: float         # metres — ground to top of parapet / roof
    north_label: str            # e.g. "FRONT (NORTH)"

    floor_bands: list[FloorBand] = Field(default_factory=list)
    openings: list[WallOpening] = Field(default_factory=list)

    # Roof geometry
    roof_type: RoofType = RoofType.FLAT
    parapet_height: float = 0.6  # metres above top floor slab (for FLAT)
    gable_height: float = 0.0    # metres above wall plate (for GABLE only)


# ---------------------------------------------------------------------------
# 3-D isometric building outline
# ---------------------------------------------------------------------------


class IsoVertex(BaseModel):
    """A single vertex in 3D, in metres."""

    x: float
    y: float
    z: float


class IsoEdge(BaseModel):
    """An edge (line) connecting two vertices by index into the vertex list."""

    start: int
    end: int
    is_roof_edge: bool = False


class BuildingOutline3D(BaseModel):
    """
    Wireframe / isometric 3-D representation of the building massing.

    Generated from the footprint extruded to each floor height, plus roof geometry.
    Used for the isometric DXF sheet and browser SVG preview.
    """

    vertices: list[IsoVertex] = Field(default_factory=list)
    edges: list[IsoEdge] = Field(default_factory=list)
    # Bounding box for scaling
    bbox_x: float = 0.0
    bbox_y: float = 0.0
    bbox_z: float = 0.0


# ---------------------------------------------------------------------------
# Complete elevation set (all 4 faces + 3D outline)
# ---------------------------------------------------------------------------


class ElevationSet(BaseModel):
    """All elevation outputs generated by the elevation engine for one design."""

    design_id: str
    front: ElevationView | None = None
    rear: ElevationView | None = None
    left: ElevationView | None = None
    right: ElevationView | None = None
    outline_3d: BuildingOutline3D | None = None

    def get_face(self, face: ElevationFace) -> ElevationView | None:
        return {
            ElevationFace.FRONT: self.front,
            ElevationFace.REAR: self.rear,
            ElevationFace.LEFT: self.left,
            ElevationFace.RIGHT: self.right,
        }[face]
